### ISSUE TITLE
APIにPOSTした際のrequest bodyの値がおかしい

### ISSUE THREAD

**Issue by YukiYuigishi** [Growthers/misskey-invite-front#1]
POST　/api/v1/request をした際のrequest bodyの値が
```json
{ "email": ""}
```
となる
恐らく、うまくformが取得できていない

**Comment by Yusuke4869** [comment]
https://github.com/Growthers/misskey-invite-front/commit/5a78894d64f94fcba3bc1882c8b7fbc8905cf769 で修正
